#ifndef MY_RUST_LIB_H
#define MY_RUST_LIB_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct MyRng MyRng;

struct MyRng *rng_new(void);

uint32_t rng_gen(struct MyRng *self);

void rng_free(struct MyRng *self);

#endif /* MY_RUST_LIB_H */
