[package]
name = "broken-prng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
rand_chacha = { version = "0.3.1", features = ["simd"] }
